# This workflow will lint python code with flake8 and flake8-nb.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Check sorted python imports using isort
      run: |
        isort . -c
    - name: Lint code with flake8
      run: |
        flake8 --max-line-length=119 --exclude=.git/,__pycache__/,dist/ .
